version: '3.8'

services:
  web:
    build: .
    container_name: merchandising
    ports:
      - 8000:8000
    volumes:
      - .:/src
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env

volumes:
  postgres_data: