name: merchandising workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_push_backend_to_docker_hub:
    if: github.ref == 'refs/heads/main'
    name: Push backend Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: nick0901
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: 'nick0901/merchandising_backend:latest'
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8
          pip install isort
          pip install -r requirements.txt 
      - name: Test with flake8 and isort
        run: |
          isort .
          python -m flake8
      - name: Run Tests
        run: |
          pytest
